swagger: "2.0"
info:
  title: Device Manager
  version: 0.1.0
basePath: /api
produces:
- application/json
consumes:
- application/json
schemes:
- http
securityDefinitions:
  User:
    type: apiKey
    name: Authorization
    in: header
  Device:
    type: apiKey
    name: Authorization
    in: header
paths:
  /users:
    $ref: './users.yaml'
  /devices:
    $ref: './devices.yaml'
  /devices/readings:
    $ref: './device_readings.yaml'
  /devices/{device_id}/stats:
    $ref: './device_stats.yaml'

definitions:
  JWTKey:
    type: object
    properties:
      id:
        type: string
        x-isnullable: false
      email:
        type: string
        x-isnullable: true
      type:
        type: string
        x-isnullable: false
