swagger: "2.0"
info:
  title: Device Manager
  version: 0.1.0
basePath: /api
produces:
- application/json
consumes:
- application/json
schemes:
- http
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /users:
    $ref: './users.yaml'
  /devices:
    $ref: './devices.yaml'
  /devices/{device_id}/stats:
    $ref: './device_stats.yaml'