// Code generated by ifacemaker. DO NOT EDIT.

package interfaces

import (
	"github.com/Speakerkfm/device-manager/pkg/models"

	"github.com/dgrijalva/jwt-go"
)

type JWT interface {
	CreateJWT(entity interface{}, entityType string) (string, error)
	ValidateUserToken(token string) (*models.AuthKey, error)
	ValidateDeviceToken(token string) (*models.AuthKey, error)
	Parse(tokenString, jwtSecret string) (jwt.MapClaims, bool)
}
