// Code generated by ifacemaker. DO NOT EDIT.

package serviceiface

import (
	"device-manager/pkg/models"
)

type DeviceService interface {
	NewDevice(ownerEmail, deviceName string) (string, error)
	GetUserDevices(userEmail string) ([]*models.Device, error)
	GetDeviceStats(deviceID string) ([]*models.DeviceReadings, error)
	SaveDeviceReadings(deviceID string, readingsTime string, temperature float64) error
}
