// Code generated by ifacemaker. DO NOT EDIT.

package serviceiface

import (
	"device-manager/pkg/models"
)

type DeviceService interface {
	NewDevice(user *models.User, deviceName string) (string, error)
}
