// Code generated by ifacemaker. DO NOT EDIT.

package serviceiface

import (
	"device-manager/pkg/models"

	"github.com/dgrijalva/jwt-go"
)

type JWT interface {
	CreateJWT(entity interface{}, entityType string) (string, error)
	ValidateUserToken(token string) (*models.JWTKey, error)
	ValidateDeviceToken(token string) (*models.JWTKey, error)
	Parse(tokenString, jwtSecret string) (jwt.MapClaims, bool)
}
