// Code generated by ifacemaker. DO NOT EDIT.

package store

import (
	"device-manager/pkg/models"
)

type StoreInterface interface {
	NewDevice(user *models.User, deviceName, ownerEmail string) (*models.Device, error)
	NewUser(email string) (*models.User, error)
	GetUserByEmail(email string) (*models.User, error)
}
