// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "device-manager/pkg/models"
)

// DeviceStatsOKCode is the HTTP code returned for type DeviceStatsOK
const DeviceStatsOKCode int = 200

/*DeviceStatsOK OK

swagger:response deviceStatsOK
*/
type DeviceStatsOK struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewDeviceStatsOK creates DeviceStatsOK with default headers values
func NewDeviceStatsOK() *DeviceStatsOK {

	return &DeviceStatsOK{}
}

// WithPayload adds the payload to the device stats o k response
func (o *DeviceStatsOK) WithPayload(payload interface{}) *DeviceStatsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the device stats o k response
func (o *DeviceStatsOK) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeviceStatsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// DeviceStatsUnauthorizedCode is the HTTP code returned for type DeviceStatsUnauthorized
const DeviceStatsUnauthorizedCode int = 401

/*DeviceStatsUnauthorized Пользователь не аутентифицирован в системе

swagger:response deviceStatsUnauthorized
*/
type DeviceStatsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResult `json:"body,omitempty"`
}

// NewDeviceStatsUnauthorized creates DeviceStatsUnauthorized with default headers values
func NewDeviceStatsUnauthorized() *DeviceStatsUnauthorized {

	return &DeviceStatsUnauthorized{}
}

// WithPayload adds the payload to the device stats unauthorized response
func (o *DeviceStatsUnauthorized) WithPayload(payload *models.ErrorResult) *DeviceStatsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the device stats unauthorized response
func (o *DeviceStatsUnauthorized) SetPayload(payload *models.ErrorResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeviceStatsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeviceStatsUnprocessableEntityCode is the HTTP code returned for type DeviceStatsUnprocessableEntity
const DeviceStatsUnprocessableEntityCode int = 422

/*DeviceStatsUnprocessableEntity Error

swagger:response deviceStatsUnprocessableEntity
*/
type DeviceStatsUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResult `json:"body,omitempty"`
}

// NewDeviceStatsUnprocessableEntity creates DeviceStatsUnprocessableEntity with default headers values
func NewDeviceStatsUnprocessableEntity() *DeviceStatsUnprocessableEntity {

	return &DeviceStatsUnprocessableEntity{}
}

// WithPayload adds the payload to the device stats unprocessable entity response
func (o *DeviceStatsUnprocessableEntity) WithPayload(payload *models.ErrorResult) *DeviceStatsUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the device stats unprocessable entity response
func (o *DeviceStatsUnprocessableEntity) SetPayload(payload *models.ErrorResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeviceStatsUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
