// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"
	validate "github.com/go-openapi/validate"

	models "device-manager/pkg/models"
)

// DeviceListHandlerFunc turns a function with the right signature into a device list handler
type DeviceListHandlerFunc func(DeviceListParams, *models.AuthKey) middleware.Responder

// Handle executing the request and returning a response
func (fn DeviceListHandlerFunc) Handle(params DeviceListParams, principal *models.AuthKey) middleware.Responder {
	return fn(params, principal)
}

// DeviceListHandler interface for that can handle valid device list params
type DeviceListHandler interface {
	Handle(DeviceListParams, *models.AuthKey) middleware.Responder
}

// NewDeviceList creates a new http.Handler for the device list operation
func NewDeviceList(ctx *middleware.Context, handler DeviceListHandler) *DeviceList {
	return &DeviceList{Context: ctx, Handler: handler}
}

/*DeviceList swagger:route GET /devices devices deviceList

Получение списка устройств пользователя

*/
type DeviceList struct {
	Context *middleware.Context
	Handler DeviceListHandler
}

func (o *DeviceList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeviceListParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.AuthKey
	if uprinc != nil {
		principal = uprinc.(*models.AuthKey) // this is really a models.AuthKey, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DeviceListOKBodyItems0 device list o k body items0
// swagger:model DeviceListOKBodyItems0
type DeviceListOKBodyItems0 struct {

	// device id
	// Required: true
	DeviceID string `json:"device_id"`

	// device name
	// Required: true
	DeviceName string `json:"device_name"`

	// last meter readings time
	LastMeterReadingsTime *string `json:"last_meter_readings_time,omitempty"`
}

// Validate validates this device list o k body items0
func (o *DeviceListOKBodyItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDeviceID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDeviceName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeviceListOKBodyItems0) validateDeviceID(formats strfmt.Registry) error {

	if err := validate.RequiredString("device_id", "body", string(o.DeviceID)); err != nil {
		return err
	}

	return nil
}

func (o *DeviceListOKBodyItems0) validateDeviceName(formats strfmt.Registry) error {

	if err := validate.RequiredString("device_name", "body", string(o.DeviceName)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeviceListOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeviceListOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res DeviceListOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
